apiVersion: v1
kind: Service
metadata:
  name: zesty-ritchie-0483c4dcc8-srv
  namespace: apps-release
spec:
  selector:
    app: zesty-ritchie-0483c4dcc8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP